apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backend","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"backend"}},"template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"env":[{"name":"MONGO_URL","value":"mongodb://mongo-service:27017/mern"}],"image":"madanrayamajhi/backend:latest","name":"backend","ports":[{"containerPort":5000}]}]}}}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    generation: 2
    name: backend
    namespace: default
    resourceVersion: "14591"
    uid: a51ff089-e898-43ff-8000-c9a2aed84bc5
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: backend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: backend
      spec:
        containers:
        - env:
          - name: MONGO_URL
            value: mongodb://mongo-service:27017/mern
          image: madanrayamajhi/backend:latest
          imagePullPolicy: Always
          name: backend
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2026-05-07T09:36:30Z"
      lastUpdateTime: "2026-05-07T09:36:30Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2026-05-11T08:58:31Z"
      lastUpdateTime: "2026-05-11T08:58:31Z"
      message: ReplicaSet "backend-795685bf6" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 2
    replicas: 3
    unavailableReplicas: 3
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"frontend","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"frontend"}},"template":{"metadata":{"labels":{"app":"frontend"}},"spec":{"containers":[{"image":"madanrayamajhi/frontend:latest","name":"frontend","ports":[{"containerPort":3000}]}]}}}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    generation: 2
    name: frontend
    namespace: default
    resourceVersion: "14597"
    uid: 5d56c6a6-6da9-4dc4-bae0-492c9265c726
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: frontend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: frontend
      spec:
        containers:
        - image: madanrayamajhi/frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2026-05-07T09:36:30Z"
      lastUpdateTime: "2026-05-07T09:36:30Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2026-05-11T08:58:40Z"
      lastUpdateTime: "2026-05-11T08:58:40Z"
      message: ReplicaSet "frontend-86c476d658" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 2
    replicas: 3
    unavailableReplicas: 3
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mongo","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mongo"}},"template":{"metadata":{"labels":{"app":"mongo"}},"spec":{"containers":[{"image":"mongo:6","name":"mongo","ports":[{"containerPort":27017}]}]}}}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    generation: 1
    name: mongo
    namespace: default
    resourceVersion: "6225"
    uid: e4f3f2fd-76da-4d93-acee-c6c2d7f7edff
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mongo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mongo
      spec:
        containers:
        - image: mongo:6
          imagePullPolicy: IfNotPresent
          name: mongo
          ports:
          - containerPort: 27017
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-05-07T09:36:30Z"
      lastUpdateTime: "2026-05-07T09:38:48Z"
      message: ReplicaSet "mongo-69b7d4c9fc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-05-07T09:55:03Z"
      lastUpdateTime: "2026-05-07T09:55:03Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"backend-service","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":5000}],"selector":{"app":"backend"},"type":"ClusterIP"}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    name: backend-service
    namespace: default
    resourceVersion: "4991"
    uid: 959121d1-0c51-4e11-87fd-e521c73da954
  spec:
    clusterIP: 10.98.100.249
    clusterIPs:
    - 10.98.100.249
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      app: backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-service","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":3000}],"selector":{"app":"frontend"},"type":"LoadBalancer"}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    name: frontend-service
    namespace: default
    resourceVersion: "5003"
    uid: 6cfdf768-5a6e-4635-baf9-67c5c9c7ac29
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.110.47.238
    clusterIPs:
    - 10.110.47.238
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31658
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: frontend
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-05-07T07:52:56Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "194"
    uid: 466abf08-32e1-45b7-a9fa-f07b81e3f99d
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mongo-service","namespace":"default"},"spec":{"ports":[{"port":27017,"targetPort":27017}],"selector":{"app":"mongo"},"type":"ClusterIP"}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    name: mongo-service
    namespace: default
    resourceVersion: "5040"
    uid: 0f2f4433-bc22-4365-bc0b-b45e8b7c686e
  spec:
    clusterIP: 10.109.118.182
    clusterIPs:
    - 10.109.118.182
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  data:
    NODE_ENV: production
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"NODE_ENV":"production"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"app-config","namespace":"default"}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    name: app-config
    namespace: default
    resourceVersion: "4992"
    uid: 81ce3ecd-85d9-480d-9e0e-675df099be1e
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI2MDUwNjA3NTI0NloXDTM2MDUwNDA3NTI0NlowFTETMBEGA1UE
      AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANyn
      iAsE7Q9amqJTU52KdOy/NS9xOcOoz5XQ3S0CEmwT4pNGBCrt2qMT0gkni1/zcnbc
      krYgq0E5tdiVVtAxSS3RSq8h+4QSOBtaLYzE1c08lHfGa6M1AXAyUZ9gpSmF/Hj1
      +nNrBYoXXi1ltgrKyVXeclfvJFfZMwe18urf1zFCb4TKiL8IUo86vJZo3M4cNvxa
      xxrRX0alunhj3XvMg7aWBJOeLPCVVLR6i6D4er9l123X+DjKcoLeWmdCOhyL5v5i
      yiSSEhHWlhfw3NxehjQG6iJb0mWxhllptNyhB3cDl8n1iQcLwmZQbGS7cJWImYXv
      WPq46N9GOhxwM5Ueh3kCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
      MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
      BBTJVmVUs5YIRCv0euUvFhG1GW3RHjANBgkqhkiG9w0BAQsFAAOCAQEACXPBhrfl
      dVQOhxgousLom4vB/aAirgUZLBgCcFs0CWEH3/8NNGu9e2m+3B1NHMLozMqo1wWZ
      r57GTSFTM00Yd+WLBnvHDLLHJhPPBsqQuRKY1SLZb7ihG/KiHNItryjn+hQpIy10
      pQ25aj/vUgjpdj81wNHevmCFqcPXQRHPa3OyLLfwz3jXun0npy90c7DjWU7w1P40
      s0oct6IFfeJAKfQVy2CeA/hAFEJmVgUYgFR4qGHg2o7Cu/2NiMlQAOsAhNl6v0qJ
      vQqilMu3sfhHHLg1lH1OXqFfU2t2zbOQmcae6CzaNPnbzHYr0uI22vZ7VHRFqGQa
      Kp26xlt0QXtxxQ==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-05-07T07:53:10Z"
    name: kube-root-ca.crt
    namespace: default
    resourceVersion: "315"
    uid: 767a64fe-f0e2-4178-8b0a-4fb83af62f38
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"mern-ingress","namespace":"default"},"spec":{"rules":[{"host":"mern.local","http":{"paths":[{"backend":{"service":{"name":"frontend-service","port":{"number":80}}},"path":"/","pathType":"Prefix"},{"backend":{"service":{"name":"backend-service","port":{"number":80}}},"path":"/api","pathType":"Prefix"}]}}]}}
    creationTimestamp: "2026-05-07T09:36:30Z"
    generation: 1
    name: mern-ingress
    namespace: default
    resourceVersion: "5020"
    uid: 1a7c3eb4-da7c-45f0-91bd-4987c88e2b62
  spec:
    rules:
    - host: mern.local
      http:
        paths:
        - backend:
            service:
              name: frontend-service
              port:
                number: 80
          path: /
          pathType: Prefix
        - backend:
            service:
              name: backend-service
              port:
                number: 80
          path: /api
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
